# Generated by Django 3.2.16 on 2022-10-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(default='ictfc', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
